import { CartItem } from '@/app/types';

export const mockCartItems: CartItem[] = [
  {
    id: '1',
    productId: '1',
    name: 'Striped Flutter Sleeve Overlap Collar Peplum Hem Blouse',
    category: 'Electronics',
    price: 690,
    originalPrice: 1299,
    image: 'https://rukminim2.flixcart.com/image/832/832/xif0q/top/b/s/k/s-1211-12-a-style-fe-original-imagz262uhz8zchp.jpeg?q=70',
    rating: 4.2,
    reviewsCount: 2890,
    stock: 10,
    quantity: 1,
    seller: 'StyleFe',
    deliveryDate: 'Delivery by Sat Jan 24',
    description: 'A stylish blouse for casual wear.',
    countInStock: 20,
    images: ['https://rukminim2.flixcart.com/image/832/832/xif0q/top/b/s/k/s-1211-12-a-style-fe-original-imagz262uhz8zchp.jpeg?q=70'],
    thumbnail: 'https://rukminim2.flixcart.com/image/832/832/xif0q/top/b/s/k/s-1211-12-a-style-fe-original-imagz262uhz8zchp.jpeg?q=70'
  },
  {
    id: '2',
    productId: '2',
    name: 'Men Regular Fit Solid Cut Away Collar Casual Shirt',
    category: 'Fashion',
    price: 449,
    originalPrice: 999,
    image: 'https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/f/f/xl-c821-dark-maroon-dennis-lingo-original-imagn9yj5gzzdvf2.jpeg?q=70',
    rating: 4.0,
    reviewsCount: 15432,
    stock: 10,
    quantity: 2,
    seller: 'DENNIS LINGO',
    deliveryDate: 'Delivery by Sun Jan 25',
    description: 'Comfortable cotton shirt.',
    countInStock: 50,
    images: ['https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/f/f/xl-c821-dark-maroon-dennis-lingo-original-imagn9yj5gzzdvf2.jpeg?q=70'],
    thumbnail: 'https://rukminim2.flixcart.com/image/832/832/xif0q/shirt/g/f/f/xl-c821-dark-maroon-dennis-lingo-original-imagn9yj5gzzdvf2.jpeg?q=70'
  },
  {
    id: '3',
    productId: '3',
    name: 'APPLE iPhone 15 (Blue, 128 GB)',
    category: 'Electronics',
    price: 71999,
    originalPrice: 79900,
    image: 'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/a/x/-original-imaghxebk4xscxnw.jpeg?q=70',
    rating: 4.7,
    reviewsCount: 1200,
    stock: 5,
    quantity: 1,
    seller: 'RetailNet',
    deliveryDate: 'Delivery by Tue Jan 27',
    description: 'Latest iPhone with dynamic island.',
    countInStock: 10,
    images: ['https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/a/x/-original-imaghxebk4xscxnw.jpeg?q=70'],
    thumbnail: 'https://rukminim2.flixcart.com/image/832/832/xif0q/mobile/t/a/x/-original-imaghxebk4xscxnw.jpeg?q=70'
  },
];
